### PR TITLE
Add way to create alias within option value. Use it for migrate

### PR DESCRIPTION
**Pull request by bscheshirwork**
https://github.com/yiisoft/yii2/pull/16789

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | -
| Tests pass?   | yes/no
| Fixed issues  | #3 #4

### CODE REVIEW

**Comment by samdark** [comment]
While it's good to have a shortcut for it, I'm not sure it's the best possible choice of letter.

**Comment by bscheshirwork** [comment]
-y for yes

**Comment by samdark** [comment]
Yes, I understand that. Want @cebe, @hiqsol and @SilverFire opinions on that though.

**Comment by cebe** [comment]
having a short option that behaves differently from the long option can result in very confusing interface and is also not easy to explain in docs. I would prefer to keep it more intuitive to use.

e.g. 

```
./yii migrate --interactive
./yii migrate --non-interactive
```

The thing with boolean flags is a bit complicated, while having a boolean flag that is false when not specified, with `--interactive` we have one that is default true, so setting it to false requires the weird concept of `--interactive=0`. It might be better to drop `interactive` and replace it with something that disables interactiveness when specified, so that it is default false.

**Comment by bscheshirwork** [comment]
> intuitive to use.
Answer "yes" for question "apply something?"

Like to shell `apt update -y`

**Pull request closed without merging**
