### PR TITLE
Add yiisoft/cache

### PR DESCRIPTION
**Pull request by damasco**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ❌
| Fixed issues  |

### CODE REVIEW

**Comment by samdark** [comment]
Is it used by something?

**Comment by damasco** [comment]
> Is it used by something?

Yes, https://github.com/yiisoft/yii-console/blob/master/config/tests.php

**Comment by samdark** [comment]
I mean not in the config.

**Comment by damasco** [comment]
> I mean not in the config.

no, used only in config

**Comment by samdark** [comment]
Then it's better to remove it from config.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii-console/commit/597909b69e20685e1f8124f490ff8aae2c78b4f4

**Pull request closed without merging**
