### PR TITLE
updated version to 3.0.0-dev

### PR DESCRIPTION
**Pull request by schmunk42**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ?
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

I assume we start all 3.x packages with 3.0.0?

### CODE REVIEW

**Comment by samdark** [comment]
No. Only `yii-*` ones.

**Comment by schmunk42** [comment]
This is a `yii-*` package?!

**Comment by samdark** [comment]
He-he, yeah :)

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
