### PR TITLE
Add support for Symfony Console v5.0.

### PR DESCRIPTION
**Pull request by snickom**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ❌
| Fixed issues  | -

### CODE REVIEW

**Comment by samdark** [comment]
I think we can just require 5.0.

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by roxblnfk** [comment]
I think @snickom was right when he proposed the version `^4.3 | ^5.0`
Now some dependencies that have not migrated to version 5 cannot be installed

**Comment by samdark** [comment]
Which ones?

**Comment by samdark** [comment]
Which ones? I've just tried installing it and it's OK as is.

**Comment by roxblnfk** [comment]
`phan/phan` (PR created)
`yiisoft/yii-cycle` (i will fix it)

**Comment by samdark** [comment]
Fixed yii-cycle dependencies

**Pull request merged**
