### PR TITLE
Raise the minimum PHP version

### PR DESCRIPTION
**Pull request by rustamwin**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️
| Fixed issues  | #147

### CODE REVIEW

**Review by terabytesoftw — APPROVED** [review]

**Comment by vjik** [comment]
This change break backwards compatibility for already released package. What are the goals? Are there any other changes planned in the package?

**Comment by rustamwin** [comment]
> This change break backwards compatibility for already released package. What are the goals? Are there any other changes planned in the package?

Yes, this change can be tagged as major version.

**Review by samdark — APPROVED** [review]

**Review by devanych — APPROVED** [review]

**Comment by vjik** [comment]
Maybe right away raise to 8.1?

**Comment by rustamwin** [comment]
> Maybe right away raise to 8.1?

We do not need 8.1 in this package yet. 8.0 also supports 8.1.

**Review by vjik — APPROVED** [review]

**Pull request merged**
